service: speak-polly-app
frameworkVersion: '3'

custom:
  text_bucket: text-${self:service}-${self:provider.stage}
  audio_bucket: audio-${self:service}-${self:provider.stage}
  dynamodb_table: mp3-${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  memorySize: 128
  timeout: 100
  profile: serverless-admin
  environment:
    TEXT_BUCKET: ${self:custom.text_bucket}
    AUDIO_BUCKET: ${self:custom.audio_bucket}
    DYNAMODB_TABLE: ${self:custom.dynamodb_table}

  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:*'
          Resource:
            - 'arn:aws:s3:::${self:custom.text_bucket}/*'
            - 'arn:aws:s3:::${self:custom.text_bucket}*'
            - 'arn:aws:s3:::${self:custom.audio_bucket}/*'
            - 'arn:aws:s3:::${self:custom.audio_bucket}*'
        - Effect: Allow
          Action: 'polly:*'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:GetItem'
            - 'dynamodb:DeleteItem'
          Resource:
            - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodb_table}'
            - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodb_table}/*'

functions:
  speakPolly:
    handler: handler.speakPolly
    environment:
      VOICE_AGENT: Joanna

    events:
      - s3:
          bucket: ${self:custom.text_bucket}
          event: s3:ObjectCreated:*
          rules:
            # - prefix: transcripts/
            - suffix: .txt

# you can add CloudFormation resource templates here
resources:
  Resources:
    #     S3TextBucket:
    #       Type: AWS::S3::Bucket
    #       Properties:
    #         BucketName: ${self:custom.text_bucket}
    #         AccessControl: PublicRead
    #         VersioningConfiguration:
    #           Status: Suspended

    S3AudioBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.audio_bucket}
        AccessControl: PublicRead
        VersioningConfiguration:
          Status: Suspended

    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
